package me.moodcat.api;

import junit.framework.TestCase;

/**
 * The class <code>UserAPITest</code> contains tests for the class {@link
 * <code>UserAPI</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 6/10/15 11:58 AM
 *
 * @author Gijs Weterings
 *
 * @version $Revision$
 */
public class UserAPITest extends TestCase {

    /**
     * Construct new test instance
     *
     * @param name the test name
     */
    public UserAPITest(String name) {
        super(name);
    }
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = 
 * package = me.moodcat.api
 * package.sourceFolder = moodcat-core/src/test/java
 * superclassType = junit.framework.TestCase
 * testCase = UserAPITest
 * testClassType = UserAPI
 */